// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

#ifndef PROTOBUF_INCLUDED_address_2eproto
#define PROTOBUF_INCLUDED_address_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "building.pb.h"
#include "city.pb.h"
#include "street.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_address_2eproto 

namespace protobuf_address_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_address_2eproto
class Address;
class AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
namespace google {
namespace protobuf {
template<> ::Address* Arena::CreateMaybeMessage<::Address>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class Address : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Address) */ {
 public:
  Address();
  virtual ~Address();

  Address(const Address& from);

  inline Address& operator=(const Address& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Address(Address&& from) noexcept
    : Address() {
    *this = ::std::move(from);
  }

  inline Address& operator=(Address&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Address& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Address* internal_default_instance() {
    return reinterpret_cast<const Address*>(
               &_Address_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Address* other);
  friend void swap(Address& a, Address& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Address* New() const final {
    return CreateMaybeMessage<Address>(NULL);
  }

  Address* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Address>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Address& from);
  void MergeFrom(const Address& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Address* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .City city = 1;
  bool has_city() const;
  void clear_city();
  static const int kCityFieldNumber = 1;
  private:
  const ::City& _internal_city() const;
  public:
  const ::City& city() const;
  ::City* release_city();
  ::City* mutable_city();
  void set_allocated_city(::City* city);

  // .Street street = 2;
  bool has_street() const;
  void clear_street();
  static const int kStreetFieldNumber = 2;
  private:
  const ::Street& _internal_street() const;
  public:
  const ::Street& street() const;
  ::Street* release_street();
  ::Street* mutable_street();
  void set_allocated_street(::Street* street);

  // .Building building = 3;
  bool has_building() const;
  void clear_building();
  static const int kBuildingFieldNumber = 3;
  private:
  const ::Building& _internal_building() const;
  public:
  const ::Building& building() const;
  ::Building* release_building();
  ::Building* mutable_building();
  void set_allocated_building(::Building* building);

  // @@protoc_insertion_point(class_scope:Address)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::City* city_;
  ::Street* street_;
  ::Building* building_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_address_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Address

// .City city = 1;
inline bool Address::has_city() const {
  return this != internal_default_instance() && city_ != NULL;
}
inline const ::City& Address::_internal_city() const {
  return *city_;
}
inline const ::City& Address::city() const {
  const ::City* p = city_;
  // @@protoc_insertion_point(field_get:Address.city)
  return p != NULL ? *p : *reinterpret_cast<const ::City*>(
      &::_City_default_instance_);
}
inline ::City* Address::release_city() {
  // @@protoc_insertion_point(field_release:Address.city)
  
  ::City* temp = city_;
  city_ = NULL;
  return temp;
}
inline ::City* Address::mutable_city() {
  
  if (city_ == NULL) {
    auto* p = CreateMaybeMessage<::City>(GetArenaNoVirtual());
    city_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Address.city)
  return city_;
}
inline void Address::set_allocated_city(::City* city) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(city_);
  }
  if (city) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      city = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, city, submessage_arena);
    }
    
  } else {
    
  }
  city_ = city;
  // @@protoc_insertion_point(field_set_allocated:Address.city)
}

// .Street street = 2;
inline bool Address::has_street() const {
  return this != internal_default_instance() && street_ != NULL;
}
inline const ::Street& Address::_internal_street() const {
  return *street_;
}
inline const ::Street& Address::street() const {
  const ::Street* p = street_;
  // @@protoc_insertion_point(field_get:Address.street)
  return p != NULL ? *p : *reinterpret_cast<const ::Street*>(
      &::_Street_default_instance_);
}
inline ::Street* Address::release_street() {
  // @@protoc_insertion_point(field_release:Address.street)
  
  ::Street* temp = street_;
  street_ = NULL;
  return temp;
}
inline ::Street* Address::mutable_street() {
  
  if (street_ == NULL) {
    auto* p = CreateMaybeMessage<::Street>(GetArenaNoVirtual());
    street_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Address.street)
  return street_;
}
inline void Address::set_allocated_street(::Street* street) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(street_);
  }
  if (street) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      street = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, street, submessage_arena);
    }
    
  } else {
    
  }
  street_ = street;
  // @@protoc_insertion_point(field_set_allocated:Address.street)
}

// .Building building = 3;
inline bool Address::has_building() const {
  return this != internal_default_instance() && building_ != NULL;
}
inline const ::Building& Address::_internal_building() const {
  return *building_;
}
inline const ::Building& Address::building() const {
  const ::Building* p = building_;
  // @@protoc_insertion_point(field_get:Address.building)
  return p != NULL ? *p : *reinterpret_cast<const ::Building*>(
      &::_Building_default_instance_);
}
inline ::Building* Address::release_building() {
  // @@protoc_insertion_point(field_release:Address.building)
  
  ::Building* temp = building_;
  building_ = NULL;
  return temp;
}
inline ::Building* Address::mutable_building() {
  
  if (building_ == NULL) {
    auto* p = CreateMaybeMessage<::Building>(GetArenaNoVirtual());
    building_ = p;
  }
  // @@protoc_insertion_point(field_mutable:Address.building)
  return building_;
}
inline void Address::set_allocated_building(::Building* building) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(building_);
  }
  if (building) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      building = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, building, submessage_arena);
    }
    
  } else {
    
  }
  building_ = building;
  // @@protoc_insertion_point(field_set_allocated:Address.building)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_address_2eproto
