// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: city.proto

#ifndef PROTOBUF_INCLUDED_city_2eproto
#define PROTOBUF_INCLUDED_city_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_city_2eproto 

namespace protobuf_city_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_city_2eproto
class City;
class CityDefaultTypeInternal;
extern CityDefaultTypeInternal _City_default_instance_;
namespace google {
namespace protobuf {
template<> ::City* Arena::CreateMaybeMessage<::City>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class City : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:City) */ {
 public:
  City();
  virtual ~City();

  City(const City& from);

  inline City& operator=(const City& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  City(City&& from) noexcept
    : City() {
    *this = ::std::move(from);
  }

  inline City& operator=(City&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const City& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const City* internal_default_instance() {
    return reinterpret_cast<const City*>(
               &_City_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(City* other);
  friend void swap(City& a, City& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline City* New() const final {
    return CreateMaybeMessage<City>(NULL);
  }

  City* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<City>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const City& from);
  void MergeFrom(const City& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(City* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string zip_code = 2;
  void clear_zip_code();
  static const int kZipCodeFieldNumber = 2;
  const ::std::string& zip_code() const;
  void set_zip_code(const ::std::string& value);
  #if LANG_CXX11
  void set_zip_code(::std::string&& value);
  #endif
  void set_zip_code(const char* value);
  void set_zip_code(const char* value, size_t size);
  ::std::string* mutable_zip_code();
  ::std::string* release_zip_code();
  void set_allocated_zip_code(::std::string* zip_code);

  // string country_name = 3;
  void clear_country_name();
  static const int kCountryNameFieldNumber = 3;
  const ::std::string& country_name() const;
  void set_country_name(const ::std::string& value);
  #if LANG_CXX11
  void set_country_name(::std::string&& value);
  #endif
  void set_country_name(const char* value);
  void set_country_name(const char* value, size_t size);
  ::std::string* mutable_country_name();
  ::std::string* release_country_name();
  void set_allocated_country_name(::std::string* country_name);

  // @@protoc_insertion_point(class_scope:City)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr zip_code_;
  ::google::protobuf::internal::ArenaStringPtr country_name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_city_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// City

// string name = 1;
inline void City::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& City::name() const {
  // @@protoc_insertion_point(field_get:City.name)
  return name_.GetNoArena();
}
inline void City::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:City.name)
}
#if LANG_CXX11
inline void City::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:City.name)
}
#endif
inline void City::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:City.name)
}
inline void City::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:City.name)
}
inline ::std::string* City::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:City.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* City::release_name() {
  // @@protoc_insertion_point(field_release:City.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void City::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:City.name)
}

// string zip_code = 2;
inline void City::clear_zip_code() {
  zip_code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& City::zip_code() const {
  // @@protoc_insertion_point(field_get:City.zip_code)
  return zip_code_.GetNoArena();
}
inline void City::set_zip_code(const ::std::string& value) {
  
  zip_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:City.zip_code)
}
#if LANG_CXX11
inline void City::set_zip_code(::std::string&& value) {
  
  zip_code_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:City.zip_code)
}
#endif
inline void City::set_zip_code(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  zip_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:City.zip_code)
}
inline void City::set_zip_code(const char* value, size_t size) {
  
  zip_code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:City.zip_code)
}
inline ::std::string* City::mutable_zip_code() {
  
  // @@protoc_insertion_point(field_mutable:City.zip_code)
  return zip_code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* City::release_zip_code() {
  // @@protoc_insertion_point(field_release:City.zip_code)
  
  return zip_code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void City::set_allocated_zip_code(::std::string* zip_code) {
  if (zip_code != NULL) {
    
  } else {
    
  }
  zip_code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), zip_code);
  // @@protoc_insertion_point(field_set_allocated:City.zip_code)
}

// string country_name = 3;
inline void City::clear_country_name() {
  country_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& City::country_name() const {
  // @@protoc_insertion_point(field_get:City.country_name)
  return country_name_.GetNoArena();
}
inline void City::set_country_name(const ::std::string& value) {
  
  country_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:City.country_name)
}
#if LANG_CXX11
inline void City::set_country_name(::std::string&& value) {
  
  country_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:City.country_name)
}
#endif
inline void City::set_country_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  country_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:City.country_name)
}
inline void City::set_country_name(const char* value, size_t size) {
  
  country_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:City.country_name)
}
inline ::std::string* City::mutable_country_name() {
  
  // @@protoc_insertion_point(field_mutable:City.country_name)
  return country_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* City::release_country_name() {
  // @@protoc_insertion_point(field_release:City.country_name)
  
  return country_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void City::set_allocated_country_name(::std::string* country_name) {
  if (country_name != NULL) {
    
  } else {
    
  }
  country_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), country_name);
  // @@protoc_insertion_point(field_set_allocated:City.country_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_city_2eproto
